services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        DOCKER_BUILDKIT: 1
    container_name: nextJS_app
    ports:
      - "${EXTERNAL_PORT}:3000"
    env_file:
      - .env